### ISSUE TITLE
Couldn't use this gem

### ISSUE THREAD

**Issue by sergeymavrin** [ankane/ignite-ruby#2]
Hi. Tried to use this gem in such way
```
require 'ignite'

class MyIgnite
  def initialize(cfg)
    client = Ignite::Client.new(host: cfg['ignite']['host'], port: cfg['ignite']['port'])
    @cache = client.get_or_create_cache('cache')
  end
end

@ignite = MyIgnite.new({ ignite: { host: 'host', port: 10_800 } })
```
but getting this error: ```./test.rb:5:in `initialize': uninitialized constant Ignite::Client (NameError)```
Can You help me? Thanks

**Comment by ankane** [comment]
Hey @sergeymavrin, try `require 'ignite/client'` instead of `require 'ignite'` (also, `cfg` should use symbols instead of strings for keys in the example - `cfg[:ignite][:host]`, etc).

**Comment by sergeymavrin** [comment]
Thank You, it's working )
Yes, hash is wrong, but it doesn't pass to parse it in connection and failed earlier
